import Head from "next/head";
import Founder from "../../components/our-leaders/Founder";
import Quote from "../../components/quote/Quote";
import CoreLeaders from "../../components/core-leaders/CoreLeaders";

export const getStaticProps = async () => {
  const management = await fetch(
    `https://sitefinityheadlesscmsapi.idealake.com/api/idealake/teams?$expand=*&$orderby=DateCreated asc`,
    {
      headers: {
        Authorization: process.env.REACT_APP_API_KEY,
      },
    }
  );
  const managementres = await management.json();
  const core = await fetch(
    `https://sitefinityheadlesscmsapi.idealake.com/api/idealake/coreleaders?$expand=*`,
    {
      headers: {
        Authorization: process.env.REACT_APP_API_KEY,
      },
    }
  );
  const coreLeaders = await core.json();

  const title = await fetch(
    `https://sitefinityheadlesscmsapi.idealake.com/api/idealake/contentitems?$filter=contains(Title,'Our Team Title')`,
    {
      headers: {
        Authorization: process.env.REACT_APP_API_KEY,
      },
    }
  );
  const titleres = await title.json();

  const subtitle = await fetch(
    `https://sitefinityheadlesscmsapi.idealake.com/api/idealake/contentitems?$filter=contains(Title,'Our Team Subtitle')`,
    {
      headers: {
        Authorization: process.env.REACT_APP_API_KEY,
      },
    }
  );
  const subtitleres = await subtitle.json();

  return {
    props: { data: managementres, datas: coreLeaders, titleres, subtitleres },
  };
};

export default function Home({ data, datas, titleres, subtitleres }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Founder
        val={data.value}
        title={titleres.value[0].Content}
        sub={subtitleres.value[0].Content}
      />
      <Quote />
      <CoreLeaders rec={datas.value} />
    </>
  );
}
